services:
  db:
    image: postgres:16.0
    env_file:
      - backend/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - db_cafeOrders_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=true"  # Отключение безопасности
      - "xpack.security.transport.ssl.enabled=false"  # Отключение SSL
    env_file:
      - backend/.env
    ports:
      - "9201:9200"  # Порт для HTTP
    volumes:
      - es_data:/usr/share/elasticsearch/data

  redis:
    image: redis:7.4.2

  cafe:
    image: cafe:1.0
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - backend/.env
    ports:
      - "8001:8000"
    depends_on:
      - db
      - elasticsearch
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cafe


  alembic_service:
    image: alembic_service:1.0
    build:
      context: ./backend
      dockerfile: ./alembic_service/Dockerfile
    env_file:
      - backend/alembic_service/.env
    depends_on:
      db:
        condition: service_healthy

    volumes:
      - ./backend/alembic_service/alembic/versions:/app/alembic_service/alembic/versions

volumes:
  db_cafeOrders_data:
  es_data:
